### ISSUE TITLE
Separate equil_input from ETS wrapper

### ISSUE THREAD

**Issue by olivhoenen** [vecma-ipp/MFW#1]
I am not 100% sure how to best tackle this one within the standalone/src part, so I will start a new feature branch not to disrupt any work from @jlakhlili or Roland.

**Comment by olivhoenen** [comment]
Quick question for @DavidPCoster: I was browsing the code of the equilibrium_input module from ETS, and found that in addition to equil_input (for which I will generate a separate 'component') there is also ets_input(equilibrium_in, coreprof_out) that "updates the q-profile in the COREPROF". Is this to be used prior to call the ITM_ETS routine or is this old code or for specific use cases? (at the moment this is not used at all in our ComPat/VECMA WF).

**Comment by DavidPCoster** [comment]
Whether this is done by a separate actor or by the main ETS is a design choice.  Bruce, in his workflows, does this outside.  I'm not sure where we do this in the ETS Kepler workflow.  As for the fortran workflow, that is yet another question which will require some digging.
If you want me to do the digging, I will try to get to this sometime ion the next few weeks.

**Comment by olivhoenen** [comment]
Ok thanks for the info. I can try do dig myself then, and ask Denis or Dmitriy for confirmation if the code itself is not very explicit.

**Comment by olivhoenen** [comment]
From Denis: 

> "I am not sure it is needed in all cases.... If I remember the purpose was to update the grid, which might be duplicated in convert cpo to ets routine."

So I am not doing anything with that ets_input routine at the moment. (unless someone wants to check impact on old ComPat results, @onnieluk let me know if you wish to try and need something from me).

I just pushed additional "standalone" module with modified existing ones (ets outputs only coreprof now). @jlakhlili let me know how you would like to proceed from here: 
- create PR to test/merge back to main develop branch
- or do you want to experiment first with this feature branch?

**Comment by olivhoenen** [comment]
Merged directly after discussion with Jalal.
