### ISSUE TITLE
Validation prototypes

### ISSUE THREAD

**Issue by jlakhlili** [vecma-ipp/MFW#3]
Validation: are the simulation results match the experimental data?

The following figure shows an example of electron density and temperature profiles drawn from experimentation:
![36309_2000_Te_ne](https://user-images.githubusercontent.com/16169832/63062730-357d0d00-befa-11e9-8b59-ce619c1313ba.png)
 It's about the mean `μ` and the standard deviation spread `σ⁻, σ⁺` for each profile at some point.

To perform the validation prototype for this example we propose to:
1.  Compute density estimation `p_exp` from observed data (`μ, σ⁻, σ⁺` values).
2.  Compare it to `p_num`, the output density after the UQ workflow the same quantity of interest.

Two first solutions:

 **Hellinger distance** for discrete probability distributions:
``` python
def hellinger(p_exp, p_num):
    return np.sqrt(np.sum((np.sqrt(p_num) - np.sqrt(p_exp)) ** 2)) / np.sqrt(2)
```
**Kullback–Leibler entropy** to measure  how `p_num` diverges from the expected distribution `p_exp`.

``` python
def KL_entropy(p_exp, p_num):
    return (p_num * np.log(p_num/p_exp)).sum()
```

**Comment by djgroen** [comment]
I think the idea is to generalize this to a VVP over time, right?

It is not really clear how the stdevs are taken along in the two validation functions. Would you be able to clarify that perhaps?

**Comment by jlakhlili** [comment]
Yes, the idea is to have a generic VVP that can be generalized over time. 

For the moment, I just propose two functions commonly used to measure loss and distances between two distributions. To compute those distributions, we need a certain number of shots, but I don't know in this stage if *stdevs* are necessaryor not. I am investigating how to use what we have from experimentation. Several possibilities to consider (like Kernel Density Estimation). 

Otherwise, we can use another simpler routine to computes distance, but It gives less information:
``` python
def mean_distance(mean_exp, stdv_exp, mean_num, stdv_exp):
   return np.sqrt(np.sum((mean_num - mean_exp) ** 2)) /  np.sqrt((stdv_num)**2 + (stdvp_exp) ** 2)
```
